### ISSUE TITLE
I have a question,help me

### ISSUE THREAD

**Issue by guohuihot** [shagabutdinov/sublime-keymap-enhanced#2]
Oh, there is a problem, help me, you have a lot of plug-ins, but I do not use it, I want to list all the files in the current file's folder, and then i can select a file and open it, as if this plugin(filelist) can meet my needs, but I do not know how to trigger it, can write a detailed document, and now the document is very difficult to understand

**Comment by shagabutdinov** [comment]
Plugin what you are talking about is called `sublime-file-dialog`. I suggest you to install sublime-file-dialog, try it and then improve the docs (open a pull request). Or at least specify what in the docs should be improved. 

P.S. Please, do not open random issues; you can write me email or open an issue in specific repo.
